"""Initial migration

Revision ID: cf4a87e3b19b
Revises: 2f8221343b14
Create Date: 2025-01-20 01:33:17.715562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf4a87e3b19b'
down_revision: Union[str, None] = '2f8221343b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('code', sa.String(length=255), nullable=True))
    op.add_column('promo_codes', sa.Column('codes', sa.JSON(), nullable=True))
    op.add_column('promo_codes', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('promo_codes', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('promo_codes', sa.Column('active_from', sa.Date(), nullable=True))
    op.add_column('promo_codes', sa.Column('active_until', sa.Date(), nullable=True))
    op.drop_column('promo_codes', 'unique_values')
    op.drop_column('promo_codes', 'value')
    op.drop_column('promo_codes', 'activations_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('activations_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promo_codes', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('promo_codes', sa.Column('unique_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('promo_codes', 'active_until')
    op.drop_column('promo_codes', 'active_from')
    op.drop_column('promo_codes', 'description')
    op.drop_column('promo_codes', 'limit')
    op.drop_column('promo_codes', 'codes')
    op.drop_column('promo_codes', 'code')
    # ### end Alembic commands ###
